/* Create Table Statements */

USE CarSales_DW;

CREATE TABLE DIM_VEHICLE (
	VEHICLEID INT PRIMARY KEY,
	MAKEID INT,
	MODELID INT,
	MAKE NVARCHAR(50),
	MODEL NVARCHAR(50),
	BODYSTYLE NVARCHAR(50),
	COSTPRICE DECIMAL(18,2),
	PRICE DECIMAL(18,2),
	QUANTITY INT,
	DATEMANUFACTURED DATE
);

CREATE TABLE DIM_CUSTOMER (
	CUSTOMERID INT PRIMARY KEY,
	FULLNAME NVARCHAR(60),
	GENDER NVARCHAR(6),
	DOB DATE,
	AGEGROUP NVARCHAR(15),
	CELLNO NVARCHAR(20),
	ADDRESS NVARCHAR(250),
	EMAIL NVARCHAR(100),
	COUNTRYID INT,
	COUNTRY NVARCHAR(100),
	CONTINENT NVARCHAR(50),
	DATEREGISTERED DATE,
	STATUSID INT,
	CUSTOMERSTATUS NVARCHAR(50)
);

CREATE TABLE DIM_STAFF (
	STAFFID NUMERIC PRIMARY KEY,
	FULLNAME NVARCHAR(60),
	GENDER NVARCHAR(6),
	DOB DATE,
	AGEGROUP NVARCHAR(15),
	CELLNO NVARCHAR(20),
	ADDRESS NVARCHAR(250),
	EMAIL NVARCHAR(100),
	BRANCHID INT,
	BRANCHNAME NVARCHAR(50),
	COUNTRYID INT,
	COUNTRY NVARCHAR(100),
	CONTINENT NVARCHAR(50),
	POSITIONID INT,
	POSITIONNAME NVARCHAR(50),
	STATUSID INT,
	STAFFSTATUS NVARCHAR(50),
	DATEJOINED DATE
);

CREATE TABLE DIM_BRANCH (
	BRANCHID INT PRIMARY KEY,
	BRANCHNAME NVARCHAR(50),
	TELNO NVARCHAR(50),
	ADDRESS NVARCHAR(250),
	EMAIL NVARCHAR(100),
	COUNTRYID INT,
	COUNTRY NVARCHAR(100),
	CONTINENT NVARCHAR(50)
);

CREATE TABLE FACT_SALES (
	TRANID NUMERIC PRIMARY KEY,
	DATEKEY NUMERIC,
	TRANDATE DATE,
	TIMEKEY NUMERIC,
	TRANTIME TIME,
	CUSTOMERID INT,
	VEHICLEID INT,
	PRICE DECIMAL(18,2),
	QUANTITY INT,
	AMOUNT DECIMAL(18,2),
	BRANCHID INT,
	STAFFID INT,
	STATUSID NUMERIC,
	TRANSACTIONSTATUS NVARCHAR(50),
	STATUSREASON NVARCHAR(250)
);

CREATE TABLE DIM_TIME (
	TIMEKEY NUMERIC PRIMARY KEY,
	[HOUR] INT,
	TIMEFROM TIME,
	TIMETO TIME,
	AMPM NVARCHAR(2)
);

CREATE TABLE DIM_DATE(
	DATEKEY	NUMERIC PRIMARY KEY,
	[DATE] DATE,
	[DAY] INT,
	[WEEKDAY] INT,
	WEEKDAYNAME	NVARCHAR(10),
	SHORTWEEKDAYNAME NVARCHAR(4),
	[DAYOFYEAR]	INT,
	WEEKOFMONTH	INT,
	WEEKOFYEAR	INT,
	[MONTH]	INT,
	[MONTHNAME]	NVARCHAR(10),
	SHORTMONTHNAME	NVARCHAR(3),
	SEASON	NVARCHAR(10),
	[QUARTER] INT,
	QUARTERNAME	NVarchar(10),
	[YEAR] INT,
	MMYYYY INT,
	MONTHYEAR NVARCHAR(7),
	ISWEEKEND INT,
	ISHOLIDAY INT,
	HOLIDAYNAME	NVARCHAR(100),
	SPECIALDAYS NVARCHAR(100),
	FINANCIALYEAR INT,
	FINANCIALQUARTER INT,
	FINANCIALMONTH	INT,
	FIRSTDATEOFYEAR	DATE,
	LASTDATEOFYEAR	DATE,
	FIRSTDATEOFQUARTER DATE,
	LASTDATEOFQUARTER DATE,
	FIRSTDATEOFMONTH DATE,
	LASTDATEOFMONTH	DATE,
	FIRSTDATEOFWEEK DATE,
	LASTDATEOFWEEK DATE
);
