/* ETL Script for DIM_BRANCH */

USE CarSales_DB;

-- Variables

DECLARE @RowCount INT;
DECLARE @RowCounter INT = 1;
DECLARE @BRANCHID INT;
DECLARE @BRANCHNAME NVARCHAR(50);
DECLARE @TELNO NVARCHAR(50);
DECLARE @ADDRESS NVARCHAR(250);
DECLARE @EMAIL NVARCHAR(100);
DECLARE @COUNTRYID INT;
DECLARE @COUNTRY NVARCHAR(100);
DECLARE @CONTINENT NVARCHAR(50);


-- Get total rows in source columns
SELECT @RowCount = COUNT(*) FROM BRANCH;

WHILE @RowCounter <= @RowCount

BEGIN
USE CarSales_DB;

-- Extraction into CTE
WITH CTE AS(
	SELECT ROW_NUMBER() OVER (ORDER BY a.BRANCHID) AS ROWID,
		a.*,
		b.COUNTRY, b.CONTINENT
	FROM BRANCH a,
		COUNTRY b
	WHERE a.COUNTRYID = b.COUNTRYID
)

-- Transformation: Extract from CTE into variables
SELECT @BRANCHID = a.BRANCHID,
	@BRANCHNAME = a.BRANCHNAME,
	@TELNO = ISNULL(a.TELNO, ''),
	@ADDRESS = CAST(a.ADDRESS AS NVARCHAR),
	@EMAIL = ISNULL(a.EMAIL, ''),
	@COUNTRYID = a.COUNTRYID, 
	@COUNTRY = ISNULL(a.COUNTRY, ''),
	@CONTINENT = ISNULL(a.CONTINENT, '')
FROM CTE a
WHERE a.ROWID = @RowCounter
ORDER BY a.BRANCHID ASC;

-- Load into DW table
USE CarSales_DW;

INSERT INTO DIM_BRANCH VALUES (@BRANCHID, @BRANCHNAME, @TELNO, @ADDRESS, @EMAIL, @COUNTRYID, @COUNTRY, @CONTINENT);
SET @RowCounter += 1;
END

/* End of ETL Script for DIM_BRANCH */