/* ETL Script for DIM_VEHICLE */

USE CarSales_DB;

-- Variables

DECLARE @RowCount INT;
DECLARE @RowCounter INT = 1;
DECLARE @VEHICLEID INT;
DECLARE @MAKEID INT;
DECLARE @MODELID INT;
DECLARE @MAKE NVARCHAR(50);
DECLARE @MODEL NVARCHAR(50);
DECLARE @BODYSTYLE NVARCHAR(50);
DECLARE @COSTPRICE DECIMAL(18,2);
DECLARE @PRICE DECIMAL(18,2);
DECLARE @QUANTITY INT;
DECLARE @DATEMANUFACTURED DATE;

-- Get total rows in source columns
SELECT @RowCount = COUNT(*) FROM VEHICLE;

WHILE @RowCounter <= @RowCount

BEGIN
USE CarSales_DB;

-- Extraction into CTE
WITH CTE AS(
	SELECT ROW_NUMBER() OVER (ORDER BY a.VEHICLEID) AS ROWID,
		a.*,
		b.MAKE,
		c.MODEL, c.BODYSTYLE
	FROM VEHICLE a,
		MAKE b,
		MODEL c
	WHERE a.MAKEID = b.MAKEID AND a.MODELID = c.MODELID
)

-- Transformation: Extract from CTE into variables
SELECT @VEHICLEID = a.VEHICLEID,
	@MAKEID = a.MAKEID,
	@MODELID = a.MODELID,
	@MAKE = a.MAKE,
	@MODEL = a.MODEL,
	@BODYSTYLE = a.BODYSTYLE,
	@COSTPRICE = a.COSTPRICE,
	@PRICE = a.PRICE,
	@QUANTITY = a.QUANTITY,
	@DATEMANUFACTURED = a.DATEMANUFACTURED
FROM CTE a
WHERE a.ROWID = @RowCounter
ORDER BY a.VEHICLEID ASC;

-- Load into DW Table
USE CarSales_DW;

INSERT INTO DIM_VEHICLE VALUES (@VEHICLEID, @MAKEID, @MODELID, @MAKE, @MODEL, @BODYSTYLE, @COSTPRICE, @PRICE, @QUANTITY, @DATEMANUFACTURED);
SET @RowCounter += 1; 
END

/* End of ETL Script for DIM_VEHICLE */