/* ETL Script for DIM_STAFF */

USE CarSales_DB;

-- Variables

DECLARE @RowCount INT;
DECLARE @RowCounter INT = 1;
DECLARE @STAFFID NUMERIC;
DECLARE @FULLNAME NVARCHAR(60);
DECLARE @GENDER NVARCHAR(6);
DECLARE @DOB DATE;
DECLARE @AGEGROUP NVARCHAR(15);
DECLARE @CELLNO NVARCHAR(20);
DECLARE @ADDRESS NVARCHAR(250);
DECLARE @EMAIL NVARCHAR(100);
DECLARE @BRANCHID INT;
DECLARE @BRANCHNAME NVARCHAR(50);
DECLARE @COUNTRYID INT;
DECLARE @COUNTRY NVARCHAR(100);
DECLARE @CONTINENT NVARCHAR(50);
DECLARE @POSITIONID INT;
DECLARE @POSITIONNAME NVARCHAR(50);
DECLARE @DATEJOINED DATE;
DECLARE @STATUSID INT;
DECLARE @STAFFSTATUS NVARCHAR(50);

-- Get total rows in source columns
SELECT @RowCount = COUNT(*) FROM STAFF;

WHILE @RowCounter <= @RowCount

BEGIN
USE CarSales_DB;

-- Extraction into CTE
WITH CTE AS(
	SELECT ROW_NUMBER() OVER (ORDER BY a.STAFFID) AS ROWID,
		a.*,
		b.STAFFSTATUS,
		c.COUNTRYID, c.COUNTRY, c.CONTINENT,
		d.POSITIONNAME,
		e.BRANCHNAME
	FROM STAFF a,
		STAFFSTATUS b,
		COUNTRY c,
		POSITION d,
		BRANCH e
	WHERE a.STATUSID = b.STATUSID AND a.POSITIONID = d.POSITIONID AND a.BRANCHID = e.BRANCHID AND c.COUNTRYID = e.COUNTRYID
)

-- Transformation: Extract from CTE into variables
SELECT @STAFFID = a.STAFFID,
	@FULLNAME = a.FIRSTNAME + ' ' + a.SURNAME,
	@GENDER = CASE WHEN a.GENDER = 'M' THEN 'Male' ELSE 'Female' END,
	@DOB = a.DOB,
	@AGEGROUP = CASE WHEN DATEDIFF(YEAR, a.DOB, GETDATE()) < 13 THEN 'Child' WHEN DATEDIFF(YEAR, a.DOB, GETDATE()) < 20 THEN 'Teenager'
	WHEN DATEDIFF(YEAR, a.DOB, GETDATE()) < 36 THEN 'Youth' WHEN DATEDIFF(YEAR, a.DOB, GETDATE()) < 51 THEN 'Adult'
	WHEN DATEDIFF(YEAR, a.DOB, GETDATE()) < 66 THEN 'Elder'  ELSE 'Senior Citizen' END,
	@CELLNO = ISNULL(a.CELLNO, ''),
	@ADDRESS = CAST(a.ADDRESS AS NVARCHAR),
	@EMAIL = ISNULL(a.EMAIL, ''),
	@BRANCHID = a.BRANCHID,
	@BRANCHNAME = ISNULL(a.BRANCHNAME, ''),
	@COUNTRYID = a.COUNTRYID,
	@COUNTRY = ISNULL(a.COUNTRY, ''),
	@CONTINENT = ISNULL(a.CONTINENT, ''),
	@POSITIONID = a.POSITIONID,
	@POSITIONNAME = a.POSITIONNAME,
	@STATUSID = a.STATUSID,
	@STAFFSTATUS = ISNULL(a.STAFFSTATUS, ''),
	@DATEJOINED = a.DATEJOINED
FROM CTE a
WHERE a.ROWID = @RowCounter
ORDER BY a.STAFFID ASC;

-- Load into DW table
USE CarSales_DW;

INSERT INTO DIM_STAFF VALUES (@STAFFID, @FULLNAME, @GENDER, @DOB, @AGEGROUP, @CELLNO, @ADDRESS, @EMAIL, @BRANCHID, @BRANCHNAME, @COUNTRYID,
@COUNTRY, @CONTINENT, @POSITIONID, @POSITIONNAME, @STATUSID, @STAFFSTATUS, @DATEJOINED);
SET @RowCounter += 1;
END

/* End of ETL Script for DIM_STAFF */
