/* ETL Script for FACT_SALES */

USE CarSales_DB;

--Extraction-Transformation-Loading all in one
WITH CTE AS(
	SELECT ROW_NUMBER() OVER ( ORDER BY a.TRANID ) AS ROWID,
		a.*, YEAR(a.TRANDATE) * 10000 + MONTH(a.TRANDATE) * 100 + DAY(a.TRANDATE) AS DATEKEY, 
			HOURS   = DATEPART(HOUR, a.TRANTIME),
			MINUTES = DATEPART(MINUTE, a.TRANTIME),
			TIMEKEY = CASE WHEN   DATEPART(MINUTE, a.TRANTIME) <=30 THEN DATEPART(HOUR, a.TRANTIME) ELSE DATEPART(HOUR, a.TRANTIME)+1 END,
		b.TRANSACTIONSTATUS, b.DESCRIPTION 
	   FROM SALESTRANSACTION a,
		TRANSACTIONSTATUS b
	   WHERE a.STATUSID = b.STATUSID   
)
		 
--Loading data into DW table 

INSERT INTO CarSales_DW.dbo.FACT_SALES 
SELECT TRANID, DATEKEY, TRANDATE, TIMEKEY, TRANTIME, CUSTOMERID, VEHICLEID, PRICE, QUANTITY, AMOUNT, BRANCHID, STAFFID, STATUSID, 
	TRANSACTIONSTATUS, STATUSREASON
FROM CTE;

/* End of ETL Script for FACT_SALES */